### ISSUE TITLE
Error: Patch Already Applied

### ISSUE THREAD

**Issue by ArtHuge** [z3y/XatlasLightmap#1]
Patch Already Applied
UnityEngine.Debug:LogError (object)
z3y.XatlasPackerBakeryPatch:PatchBakery () (at Assets/ArtEditor/Script/XatlasLightmap-main/Scripts/Editor/XatlasPackerBakeryPatch.cs:41)

**Comment by z3y** [comment]
This hasnt been tested on latest bakery versions so there is always a chance that it will break. I will look into it if thats the case

**Comment by ArtHuge** [comment]
I think your script is way cooler than the 2UV bakery thing. I'm really excited to see it get even better. If you put this script up for sale in the AssetStore, I'll totally buy it for sure.

**Comment by z3y** [comment]
There is nothing broken with the latest Bakery version, it still works just fine. Make sure you are on the latest version `Bakery > Utilities > Check for patches`
![image](https://github.com/z3y/XatlasLightmap/assets/33181641/450b1e1a-75bd-41eb-8376-472ec66dcc22)
