### ISSUE TITLE
How can I view the lightmap UV after packing is completed, rather than being able to view it only after baking?

### ISSUE THREAD

**Issue by ArtHuge** [z3y/XatlasLightmap#3]
Hello, your script is fantastic! It's very helpful to me. However, I have a question to ask you. Is it possible to directly view the lightmap UV distribution of the scene after clicking the pack button, instead of being able to view it only after baking?

**Comment by z3y** [comment]
Thank you! It doesnt really have anything to do with this tool, this is just how unity works. If the object has not been previously lightmapped it wont show the preview on the mesh renderer.
