### ISSUE TITLE
Pack on Render script fails when the world gets built.

### ISSUE THREAD

**Issue by JustRocs** [z3y/XatlasLightmap#4]
![2024-06-25-14-14-Unity_eOuFQeSJyA](https://github.com/z3y/XatlasLightmap/assets/106703271/23dc0d2d-241b-42a3-a525-37869cdd6646)

**Comment by z3y** [comment]
i guess unity forgor what the Editor folder does, it worked fine for me but ill add the ifdefs, thanks
