### ISSUE TITLE
XatlasPackerBakeryPatch.cs match failure on newer Bakery builds

### ISSUE THREAD

**Issue by teehzero** [z3y/XatlasLightmap#5]
The string matcher looks for `const string Patch1Start = "ftUVGBufferGen.StartUVGBuffer(res, hasEmissive, bakeWithNormalMaps);";`, which is not present in dev builds of Bakery. Changing this to `const string Patch1Start = "ftUVGBufferGen.StartUVGBuffer(res, hasEmissive, bakeWithNormalMaps, vertexBakeSampleBufferSize);";` appears to allow the patcher to function as intended.

**Comment by z3y** [comment]
fixed
